# Generated by Django 5.2 on 2025-05-30 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statuses", "0003_alter_status_created_at"),
        ("tasks", "0002_task_author_alter_task_executor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="author",
            field=models.ForeignKey(
                help_text="User who created the task",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="executor",
            field=models.ForeignKey(
                help_text="User responsible for the task",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="executor_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Executor",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.ForeignKey(
                help_text="Current task status",
                on_delete=django.db.models.deletion.PROTECT,
                to="statuses.status",
                verbose_name="Status",
            ),
        ),
    ]
