# Generated by Django 5.2 on 2025-05-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labels", "0001_initial"),
        ("tasks", "0006_alter_task_executor"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="labels",
            field=models.ManyToManyField(
                blank=True,
                help_text="Current task label",
                null=True,
                to="labels.label",
                verbose_name="Label",
            ),
        ),
    ]
