# Generated by Django 5.2 on 2025-06-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labels", "0001_initial"),
        ("tasks", "0007_task_labels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="labels",
            field=models.ManyToManyField(
                blank=True,
                help_text="Current task label",
                to="labels.label",
                verbose_name="Label",
            ),
        ),
    ]
