# Generated by Django 5.2 on 2025-07-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0008_alter_task_labels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Detailed task description",
                max_length=500,
                verbose_name="Description",
            ),
        ),
    ]
