name: CI/CD Pipeline

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Hatch
        run: pip install hatch

      - name: Create virtual environment with Hatch
        run: hatch env create

      - name: Set up Docker
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        uses: docker/compose-action@v3
        with:
          version: "v2.24.7"

      - name: Cleanup old containers
        run: docker-compose -f docker-compose.yml down --remove-orphans || true

      - name: Build containers
        run: docker-compose -f docker-compose.yml
