# Generated by Django 5.2 on 2025-05-26 13:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statuses", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="status",
            name="description",
        ),
        migrations.RemoveField(
            model_name="status",
            name="is_active",
        ),
        migrations.AddField(
            model_name="status",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
