# Generated by Django 5.2 on 2025-05-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statuses", "0002_remove_status_description_remove_status_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
